name: Merge from Pipeline to Main

on:
  push:
    branches:
      - pipeline 
jobs:
  sync_pipeline_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"

      - name: Merge pipeline into main
        run: |
          git fetch origin
          git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/IndraNaik/Networking.git main
